export const FETCH_CONTAINER = "FETCH_CONTAINER";
export const FETCH_CONTAINER_FAILED = "FETCH_CONTAINER_FAILED";
export const FETCH_CONTAINER_SUCCESS = "FETCH_CONTAINER_SUCCESS";

export const FETCH_CONTAINERS = "FETCH_CONTAINERS";
export const FETCH_CONTAINERS_FAILED = "FETCH_CONTAINERS_FAILED";
export const FETCH_CONTAINERS_SUCCESS = "FETCH_CONTAINERS_SUCCESS";

export const FETCH_CONTAINERS_BY_SUPPLIER = "FETCH_CONTAINERS_BY_SUPPLIER";
export const FETCH_CONTAINERS_BY_SUPPLIER_FAILED =
  "FETCH_CONTAINERS_BY_SUPPLIER_FAILED";
export const FETCH_CONTAINERS_BY_SUPPLIER_SUCCESS =
  "FETCH_CONTAINERS_BY_SUPPLIER_SUCCESS";

export const CREATE_CONTAINER = "CREATE_CONTAINER";
export const CREATE_CONTAINER_FAILED = "CREATE_CONTAINER_FAILED";
export const CREATE_CONTAINER_SUCCESS = "CREATE_CONTAINER_SUCCESS";

export const UPDATE_CONTAINER = "UPDATE_CONTAINER";
export const UPDATE_CONTAINER_FAILED = "UPDATE_CONTAINER_FAILED";
export const UPDATE_CONTAINER_SUCCESS = "UPDATE_CONTAINER_SUCCESS";
