export const FETCH_AUCTION_DETAILS = "FETCH_AUCTION_DETAILS";
export const FETCH_AUCTION_DETAILS_SUCCESS = "FETCH_AUCTION_DETAILS_SUCCESS";
export const FETCH_AUCTION_DETAILS_FAILED = "FETCH_AUCTION_DETAILS_FAILED";

export const FETCH_AUCTIONS = "FETCH_AUCTIONS";
export const FETCH_AUCTIONS_SUCCESS = "FETCH_AUCTIONS_SUCCESS";
export const FETCH_AUCTIONS_FAILED = "FETCH_AUCTIONS_FAILED";

export const FETCH_MANIFEST_RECORDS = "FETCH_MANIFEST_RECORDS";
export const FETCH_MANIFEST_RECORDS_SUCCESS = "FETCH_MANIFEST_RECORDS_SUCCESS";
export const FETCH_MANIFEST_RECORDS_FAILED = "FETCH_MANIFEST_RECORDS_FAILED";

export const FETCH_MONITORING = "FETCH_MONITORING";
export const FETCH_MONITORING_SUCCESS = "FETCH_MONITORING_SUCCESS";
export const FETCH_MONITORING_FAILED = "FETCH_MONITORING_FAILED";

export const FETCH_REGISTERED_BIDDERS = "FETCH_REGISTERED_BIDDERS";
export const FETCH_REGISTERED_BIDDERS_SUCCESS =
  "FETCH_REGISTERED_BIDDERS_SUCCESS";
export const FETCH_REGISTERED_BIDDERS_FAILED =
  "FETCH_REGISTERED_BIDDERS_FAILED";

export const CREATE_AUCTION = "CREATE_AUCTION";
export const CREATE_AUCTION_SUCCESS = "CREATE_AUCTION_SUCCESS";
export const CREATE_AUCTION_FAILED = "CREATE_AUCTION_FAILED";

export const UPLOAD_MANIFEST = "UPLOAD_MANIFEST";
export const UPLOAD_MANIFEST_SUCCESS = "UPLOAD_MANIFEST_SUCCESS";
export const UPLOAD_MANIFEST_FAILED = "UPLOAD_MANIFEST_FAILED";

export const REGISTER_BIDDER_AT_AUCTION = "REGISTER_BIDDER_AT_AUCTION";
export const REGISTER_BIDDER_AT_AUCTION_SUCCESS =
  "REGISTER_BIDDER_AT_AUCTION_SUCCESS";
export const REGISTER_BIDDER_AT_AUCTION_FAILED =
  "REGISTER_BIDDER_AT_AUCTION_FAILED";

export const FETCH_BIDDER_AUCTION_PROFILE = "FETCH_BIDDER_AUCTION_PROFILE";
export const FETCH_BIDDER_AUCTION_PROFILE_SUCCESS =
  "FETCH_BIDDER_AUCTION_PROFILE_SUCCESS";
export const FETCH_BIDDER_AUCTION_PROFILE_FAILED =
  "FETCH_BIDDER_AUCTION_PROFILE_FAILED";

export const FETCH_AUCTION_ITEM_DETAILS = "FETCH_AUCTION_ITEM_DETAILS";
export const FETCH_AUCTION_ITEM_DETAILS_SUCCESS =
  "FETCH_AUCTION_ITEM_DETAILS_SUCCESS";
export const FETCH_AUCTION_ITEM_DETAILS_FAILED =
  "FETCH_AUCTION_ITEM_DETAILS_FAILED";

export const CANCEL_ITEM = "CANCEL_ITEM";
export const CANCEL_ITEM_SUCCESS = "CANCEL_ITEM_SUCCESS";
export const CANCEL_ITEM_FAILED = "CANCEL_ITEM_FAILED";

export const REFUND_ITEM = "REFUND_ITEM";
export const REFUND_ITEM_SUCCESS = "REFUND_ITEM_SUCCESS";
export const REFUND_ITEM_FAILED = "REFUND_ITEM_FAILED";

export const REASSIGN_ITEM = "REASSIGN_ITEM";
export const REASSIGN_ITEM_SUCCESS = "REASSIGN_ITEM_SUCCESS";
export const REASSIGN_ITEM_FAILED = "REASSIGN_ITEM_FAILED";

export const ADD_ON = "ADD_ON";
export const ADD_ON_SUCCESS = "ADD_ON_SUCCESS";
export const ADD_ON_FAILED = "ADD_ON_FAILED";

export const RESET_AUCTION_ITEM = "RESET_AUCTION_ITEM";
export const RESET_REGISTERED_BIDDER = "RESET_REGISTERED_BIDDER";
export const RESET_ACTION_ITEM = "RESET_ACTION_ITEM";
export const RESET_AUCTION = "RESET_AUCTION";
