export const FETCH_AUCTION_DETAILS = "FETCH_AUCTION_DETAILS";
export const FETCH_AUCTION_DETAILS_SUCCESS = "FETCH_AUCTION_DETAILS_SUCCESS";
export const FETCH_AUCTION_DETAILS_FAILED = "FETCH_AUCTION_DETAILS_FAILED";

export const FETCH_AUCTIONS = "FETCH_AUCTIONS";
export const FETCH_AUCTIONS_SUCCESS = "FETCH_AUCTIONS_SUCCESS";
export const FETCH_AUCTIONS_FAILED = "FETCH_AUCTIONS_FAILED";

export const FETCH_MANIFEST_RECORDS = "FETCH_MANIFEST_RECORDS";
export const FETCH_MANIFEST_RECORDS_SUCCESS = "FETCH_MANIFEST_RECORDS_SUCCESS";
export const FETCH_MANIFEST_RECORDS_FAILED = "FETCH_MANIFEST_RECORDS_FAILED";

export const FETCH_MONITORING = "FETCH_MONITORING";
export const FETCH_MONITORING_SUCCESS = "FETCH_MONITORING_SUCCESS";
export const FETCH_MONITORING_FAILED = "FETCH_MONITORING_FAILED";

export const FETCH_AUCTION_BIDDERS = "FETCH_AUCTION_BIDDERS";
export const FETCH_AUCTION_BIDDERS_SUCCESS = "FETCH_AUCTION_BIDDERS_SUCCESS";
export const FETCH_AUCTION_BIDDERS_FAILED = "FETCH_AUCTION_BIDDERS_FAILED";

export const CREATE_AUCTION = "CREATE_AUCTION";
export const CREATE_AUCTION_SUCCESS = "CREATE_AUCTION_SUCCESS";
export const CREATE_AUCTION_FAILED = "CREATE_AUCTION_FAILED";

export const UPLOAD_MANIFEST = "UPLOAD_MANIFEST";
export const UPLOAD_MANIFEST_SUCCESS = "UPLOAD_MANIFEST_SUCCESS";
export const UPLOAD_MANIFEST_FAILED = "UPLOAD_MANIFEST_FAILED";

export const REGISTER_BIDDER_AT_AUCTION = "REGISTER_BIDDER_AT_AUCTION";
export const REGISTER_BIDDER_AT_AUCTION_SUCCESS =
  "REGISTER_BIDDER_AT_AUCTION_SUCCESS";
export const REGISTER_BIDDER_AT_AUCTION_FAILED =
  "REGISTER_BIDDER_AT_AUCTION_FAILED";

export const BIDDER_PAYMENT = "BIDDER_PAYMENT";
export const BIDDER_PAYMENT_SUCCESS = "BIDDER_PAYMENT_SUCCESS";
export const BIDDER_PAYMENT_FAILED = "BIDDER_PAYMENT_FAILED";

export const CANCEL_ITEM = "CANCEL_ITEM";
export const CANCEL_ITEM_SUCCESS = "CANCEL_ITEM_SUCCESS";
export const CANCEL_ITEM_FAILED = "CANCEL_ITEM_FAILED";

export const FETCH_BIDDER_AUCTION_PROFILE = "FETCH_BIDDER_AUCTION_PROFILE";
export const FETCH_BIDDER_AUCTION_PROFILE_SUCCESS =
  "FETCH_BIDDER_AUCTION_PROFILE_SUCCESS";
export const FETCH_BIDDER_AUCTION_PROFILE_FAILED =
  "FETCH_BIDDER_AUCTION_PROFILE_FAILED";
