export const FETCH_REQUIREMENTS = "FETCH_REQUIREMENTS";
export const FETCH_REQUIREMENTS_SUCCESS = "FETCH_REQUIREMENTS_SUCCESS";
export const FETCH_REQUIREMENTS_FAILED = "FETCH_REQUIREMENTS_FAILED";

export const ADD_REQUIREMENT = "ADD_REQUIREMENT";
export const ADD_REQUIREMENT_SUCCESS = "ADD_REQUIREMENT_SUCCESS";
export const ADD_REQUIREMENT_FAILED = "ADD_REQUIREMENT_FAILED";
