export const FETCH_INVENTORY_BY_CONTAINER = "FETCH_INVENTORY_BY_CONTAINER";
export const FETCH_INVENTORY_BY_CONTAINER_FAILED =
  "FETCH_INVENTORY_BY_CONTAINER_FAILED";
export const FETCH_INVENTORY_BY_CONTAINER_SUCCESS =
  "FETCH_INVENTORY_BY_CONTAINER_SUCCESS";

export const ADD_INVENTORY_TO_CONTAINER = "ADD_INVENTORY_TO_CONTAINER";
export const ADD_INVENTORY_TO_CONTAINER_FAILED =
  "ADD_INVENTORY_TO_CONTAINER_FAILED";
export const ADD_INVENTORY_TO_CONTAINER_SUCCESS =
  "ADD_INVENTORY_TO_CONTAINER_SUCCESS";
