export const AUCTION_STATUS = {
  PAID: "PAID",
  UNPAID: "UNPAID",
  CANCELLED: "CANCELLED",
  REFUNDED: "REFUNDED",
  LESS: "LESS",
  DISCREPANCY: "DISCREPANCY",
  PARTIAL: "PARTIAL",
};

export const INVENTORY_STATUS = {
  SOLD: "SOLD",
  UNSOLD: "UNSOLD",
  REBID: "REBID",
  VOID: "VOID",
};

export const PAYMENT_PURPOSE = {
  PARTIAL: "PARTIAL",
  REGISTRATION: "REGISTRATION",
  PULL_OUT: "PULL_OUT",
  REFUNDED: "REFUNDED",
  LESS: "LESS",
};

export const PAYMENT_TYPE = {
  CASH: "CASH",
  CHEQUE: "CHEQUE",
  BANK_TRANSFER: "BANK_TRANSFER",
};
