export const FETCH_BRANCH = "FETCH_BRANCH";
export const FETCH_BRANCH_SUCCESS = "FETCH_BRANCH_SUCCESS";
export const FETCH_BRANCH_FAILED = "FETCH_BRANCH_FAILED";

export const FETCH_BRANCHES = "FETCH_BRANCHES";
export const FETCH_BRANCHES_SUCCESS = "FETCH_BRANCHES_SUCCESS";
export const FETCH_BRANCHES_FAILED = "FETCH_BRANCHES_FAILED";

export const CREATE_BRANCH = "CREATE_BRANCH";
export const CREATE_BRANCH_SUCCESS = "CREATE_BRANCH_SUCCESS";
export const CREATE_BRANCH_FAILED = "CREATE_BRANCH_FAILED";

export const UPDATE_BRANCH = "UPDATE_BRANCH";
export const UPDATE_BRANCH_SUCCESS = "UPDATE_BRANCH_SUCCESS";
export const UPDATE_BRANCH_FAILED = "UPDATE_BRANCH_FAILED";

export const RESET_CREATE_BRANCH_RESPONSE = "RESET_CREATE_BRANCH_RESPONSE";
