export const RESET_PAYMENT_STATE = "RESET_PAYMENT_STATE";

export const FETCH_AUCTION_PAYMENT = "FETCH_AUCTION_PAYMENT";
export const FETCH_AUCTION_PAYMENT_SUCCESS = "FETCH_AUCTION_PAYMENT_SUCCESS";
export const FETCH_AUCTION_PAYMENT_FAILED = "FETCH_AUCTION_PAYMENT_FAILED";

export const FETCH_PAYMENT_DETAILS = "FETCH_PAYMENT_DETAILS";
export const FETCH_PAYMENT_DETAILS_SUCCESS = "FETCH_PAYMENT_DETAILS_SUCCESS";
export const FETCH_PAYMENT_DETAILS_FAILED = "FETCH_PAYMENT_DETAILS_FAILED";

export const BIDDER_PULLOUT_PAYMENT = "BIDDER_PULLOUT_PAYMENT";
export const BIDDER_PULLOUT_PAYMENT_SUCCESS = "BIDDER_PULLOUT_PAYMENT_SUCCESS";
export const BIDDER_PULLOUT_PAYMENT_FAILED = "BIDDER_PULLOUT_PAYMENT_FAILED";

export const FETCH_BIDDER_AUCTION_TRANSACTIONS =
  "FETCH_BIDDER_AUCTION_TRANSACTIONS";
export const FETCH_BIDDER_AUCTION_TRANSACTIONS_SUCCESS =
  "FETCH_BIDDER_AUCTION_TRANSACTIONS_SUCCESS";
export const FETCH_BIDDER_AUCTION_TRANSACTIONS_FAILED =
  "FETCH_BIDDER_AUCTION_TRANSACTIONS_FAILED";
