export const FETCH_AUCTION_PAYMENT = "FETCH_AUCTION_PAYMENT";
export const FETCH_AUCTION_PAYMENT_SUCCESS = "FETCH_AUCTION_PAYMENT_SUCCESS";
export const FETCH_AUCTION_PAYMENT_FAILED = "FETCH_AUCTION_PAYMENT_FAILED";
