export const FETCH_BIDDER = "FETCH_BIDDER";
export const FETCH_BIDDER_SUCCESS = "FETCH_BIDDER_SUCCESS";
export const FETCH_BIDDER_FAILED = "FETCH_BIDDER_FAILED";

export const FETCH_BIDDERS = "FETCH_BIDDERS";
export const FETCH_BIDDERS_SUCCESS = "FETCH_BIDDERS_SUCCESS";
export const FETCH_BIDDERS_FAILED = "FETCH_BIDDERS_FAILED";

export const CREATE_BIDDER = "CREATE_BIDDER";
export const CREATE_BIDDER_SUCCESS = "CREATE_BIDDER_SUCCESS";
export const CREATE_BIDDER_FAILED = "CREATE_BIDDER_FAILED";

export const UPDATE_BIDDER = "UPDATE_BIDDER";
export const UPDATE_BIDDER_SUCCESS = "UPDATE_BIDDER_SUCCESS";
export const UPDATE_BIDDER_FAILED = "UPDATE_BIDDER_FAILED";

export const FETCH_BIDDER_PAYMENT_HISTORY = "FETCH_BIDDER_PAYMENT_HISTORY";
export const FETCH_BIDDER_PAYMENT_HISTORY_SUCCESS =
  "FETCH_BIDDER_PAYMENT_HISTORY_SUCCESS";
export const FETCH_BIDDER_PAYMENT_HISTORY_FAILED =
  "FETCH_BIDDER_PAYMENT_HISTORY_FAILED";

export const RESET_CREATE_BIDDER_RESPONSE = "RESET_CREATE_BIDDER_RESPONSE";
export const RESET_ERROR = "RESET_ERROR";
