export const FETCH_BIDDER = "FETCH_BIDDER";
export const FETCH_BIDDER_SUCCESS = "FETCH_BIDDER_SUCCESS";
export const FETCH_BIDDER_FAILED = "FETCH_BIDDER_FAILED";

export const FETCH_BIDDERS = "FETCH_BIDDERS";
export const FETCH_BIDDERS_SUCCESS = "FETCH_BIDDERS_SUCCESS";
export const FETCH_BIDDERS_FAILED = "FETCH_BIDDERS_FAILED";

export const CREATE_BIDDER = "CREATE_BIDDER";
export const CREATE_BIDDER_SUCCESS = "CREATE_BIDDER_SUCCESS";
export const CREATE_BIDDER_FAILED = "CREATE_BIDDER_FAILED";

export const FETCH_BIDDER_PAYMENT_HISTORY = "FETCH_BIDDER_PAYMENT_HISTORY";
export const FETCH_BIDDER_PAYMENT_HISTORY_SUCCESS =
  "FETCH_BIDDER_PAYMENT_HISTORY_SUCCESS";
export const FETCH_BIDDER_PAYMENT_HISTORY_FAILED =
  "FETCH_BIDDER_PAYMENT_HISTORY_FAILED";
